# manipulator_controller:
#   type: effort_controllers/JointTrajectoryController
#   joints:
#     - shoulder_pan_joint
#     - shoulder_lift_joint
#     - elbow_joint
#     - wrist_1_joint
#     - wrist_2_joint
#     - wrist_3_joint
#   gains:
#     shoulder_pan_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     shoulder_lift_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     elbow_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     wrist_1_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     wrist_2_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     wrist_3_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1


# joint_state_controller:
#   type: joint_state_controller/JointStateController
#   publish_rate: 50
# controller_list:
#   - name: eff_joint_traj_controller
#     action_ns: follow_joint_trajectory
#     type: FollowJointTrajectory
#     default: True
#     joints:
#       - shoulder_pan_joint
#       - shoulder_lift_joint
#       - elbow_joint
#       - wrist_1_joint
#       - wrist_2_joint
#       - wrist_3_joint
#   - name: gripper_controller
#     action_ns: follow_joint_trajectory
#     default: True
#     type: FollowJointTrajectory
#     joints:
#       - robotiq_85_left_knuckle_joint

# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: todo_group_name
  joint_model_group_pose: todo_state_name
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
    - robotiq_85_left_knuckle_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: manipulator_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - robotiq_85_left_knuckle_joint